# numpy

In [2]:
# Numerical arrays.
import numpy as np

# Resources

## https://numpy.org/devdocs/user/absolute_beginners.html

## https://numpy.org/doc/2.1/reference/generated/numpy.array.html

# Multidimensional Homogenous Arrays

In [29]:
# A 2D array of inytegers
a = np.array([[[1,2,3],[4, 5, 6],[7, 8, 9]]])

# Show
print(a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [16]:
# Number of dimensions
print(a.ndim)

3


In [17]:
#Shape of the array
print (a.shape)

(1, 3, 3)


In [30]:
# Type of the elements
print (a.dtype)

int64


# Operations


In [26]:
# Two arrays.

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#show
print('A:')
print(A)
print('B:')
print(B)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]


In [20]:
# Adding constants
A + 5

array([[6, 7],
       [8, 9]])

In [21]:
# Adding two arrays

A + B

array([[ 6,  8],
       [10, 12]])

In [22]:
# Multiplying by a constant

A * 2

array([[2, 4],
       [6, 8]])

In [23]:
# Multiplying two arrays

A * B

array([[ 5, 12],
       [21, 32]])

In [24]:
# Matrix Multiplication

A @ B

array([[19, 22],
       [43, 50]])

# Accessing Elements

In [44]:
#Recall A

A

array([[1, 2],
       [3, 4]])

In [45]:
# Show first row (0) and second row (1)

b = A[0]
c = A[1]

A
print (b)
print (c)

[1 2]
[3 4]


In [56]:
# An arraY with lots of elements. (start point, end point, step)
X = np.arange(0,21)

#show X.
print (X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [61]:
# The first five elements
X[:5]

array([0, 1, 2, 3, 4])

In [63]:
# The elements from index 5 up
X[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [62]:
# Every second element
X[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [65]:
# Every second element
X[0:len(X):2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])